version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/forum.db
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/static:/usr/share/nginx/html:ro
    ports:
      - "80:80"

  db:
    image: sqlite
    volumes:
      - ./data:/data

volumes:
  data:
